language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
before_script:
  - if [ "${TRAVIS_PHP_VERSION:0:3}" == "5.6" ]; then export COMPOSER=composer-php5.json; fi
  - composer install
script:
  - if [ "${TRAVIS_PHP_VERSION:0:3}" != "5.6" ]; then composer lint; fi
  - composer test -- --exclude-group=docker