# This docker-compose should be up to run tests
version: "3"
services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    container_name: doctrine-migration-liquibase-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-test}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-test}
      - POSTGRES_DB=${POSTGRES_DB:-testdb}
    ports:
      - "5432:5432"

  mysql:
    image: mysql:${MYSQL_VERSION:-5.7}
    container_name: doctrine-migration-liquibase-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=${MYSQL_USER:-test}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-test}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-testdb}
    ports:
      - "3306:3306"
