# This docker-compose should be up to run tests
version: "2"
services:
  postgres-10:
    image: postgres:10
    environment:
      - POSTGRES_USER=test
    volumes:
      - "postgresql-10:/var/lib/postgresql/data"
  postgres-9:
    image: postgres:9
    environment:
      - POSTGRES_USER=test
    volumes:
      - "postgresql-9:/var/lib/postgresql/data"
  mysql-5:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    volumes:
      - "mysql-5:/var/lib/mysql"
volumes:
  postgresql-10: ~
  postgresql-9: ~
  mysql-5: ~
