name: Integration Tests

on:
  push:
    branches:
    - '*'
    pull_request:
    - '*'

jobs:
  integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mysql: ["5.7", "8.0"]
        postgres: ["13", "12", "11", "10"]

    steps:
    - uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer update --prefer-dist --no-progress --ignore-platform-reqs

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build
      env:
        MYSQL_VERSION: "${{ matrix.mysql }}"
        POSTGRES_VERSION: "${{ matrix.postgres }}"

    - name: Sleep for 60 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '60s'

    - name: Run test suite
      run: composer run-script integration

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
